### ISSUE TITLE
Непонятна логика работы аутентификации.

### ISSUE THREAD

**Issue by nkl90** [TussupbekovAdil/sandbox#3]
Вот, на примере нашей защищенной страницы...
```php
<?php
    // Аутентификация пользователя для доступа к этой странце
    // При неудаче переброс на страницу авторизации
    if (!isset($_COOKIE['login']) || !isset($_COOKIE['pass'])) {
        header("Location: /sessions/login.php");
        exit;
    }

    $content = 'Информация защищенная от анонимных пользователей!'
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Secure page</title>
</head>
<body>
    <div class="content">
        <?=$content ?>
    </div>
</body>
</html>
```
Что будет если мы сами установить кукисы, для нашего домена, например с помощь. js?
```javascript
document.cookie = "login=my_rand_user";
document.cookie = "pass=my_rand_pass";
```
Попробуй сам это проделать.

**Comment by TussupbekovAdil** [comment]
Переделал работу:
1. Избавился от работы с куками. Работа теперь происходит только с переменной $_SESSION. В страницах где необходима аутентификация пользователя происходит инициализация сессии.
2. При входе теперь записываются поля login и pass в переменную $_SESSION.
3. При аутентификации пользователя, проверяются существуют ли поля login и pass в переменной $_SESSION.
4. При выходе пользователя, полностью очищается $_SESSION функцией session_unset();
